# Generated by Django 4.0.6 on 2022-07-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='current_time',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='algorithm',
            new_name='func',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='epochs',
        ),
        migrations.RemoveField(
            model_name='mlmodel',
            name='lr',
        ),
    ]
